env:
  browser: true
  commonjs: true
  es6: true
  node: true
parserOptions:
  sourceType: module
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  camelcase:
    - 2
  no-console:
    - 0
